services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - redis

  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
